import { Check, Clock3, MapPin, UserRound, X } from 'lucide-react';
import { Link } from 'react-router-dom';
import './requests.css';

const seedRequests = [{ id: 'demo-request', tripId: 'demo-1', candidateId: 'demo-2', candidateName: 'Aarav', destination: 'Manali, India', status: 'pending', createdAt: new Date().toISOString() }];
export default function Requests() {
  const requests = JSON.parse(localStorage.getItem('tripsync_requests') || 'null') || seedRequests;
  const update = (id, status) => { const current = JSON.parse(localStorage.getItem('tripsync_requests') || 'null') || seedRequests; localStorage.setItem('tripsync_requests', JSON.stringify(current.map((r) => r.id === id ? { ...r, status } : r))); window.location.reload(); };
  return <div className="requests-page"><div className="requests-heading"><div><span className="page-eyebrow">TRAVEL CONNECTIONS</span><h1>Travel Requests</h1><p>Manage your companion requests and continue planning together.</p></div><Link to="/discover" className="primary-btn">Discover Travellers</Link></div><div className="request-tabs"><span className="active">All <b>{requests.length}</b></span><span>Pending</span><span>Accepted</span></div>{requests.length === 0 ? <section className="request-empty"><UserRound size={32}/><h2>No requests yet</h2><p>Find a compatible traveller from Discover and send a travel request.</p><Link to="/discover" className="primary-btn">Find Travellers</Link></section> : <div className="request-list">{requests.map((request) => <article className="request-card" key={request.id}><div className="request-avatar">{request.candidateName?.slice(0,1) || 'T'}</div><div className="request-main"><div className="request-title"><div><h2>{request.candidateName}</h2><p><MapPin size={14}/> {request.destination}</p></div><span className={`request-status ${request.status}`}>{request.status === 'pending' ? <Clock3 size={13}/> : request.status === 'accepted' ? <Check size={13}/> : <X size={13}/>} {request.status}</span></div><p className="request-text">Travel request for your selected trip. You can continue the conversation after the request is accepted.</p><div className="request-actions">{request.status === 'pending' ? <><button type="button" className="secondary-btn" onClick={() => update(request.id, 'declined')}>Decline</button><button type="button" className="primary-btn" onClick={() => update(request.id, 'accepted')}><Check size={15}/> Accept</button></> : request.status === 'accepted' ? <Link to="/messages" className="primary-btn">Message Traveller</Link> : <span className="declined-label">Request declined</span>}</div></div></article>)}</div>}</div>;
}
