import { useEffect, useState } from 'react';
import { ArrowLeft, CalendarDays, Check, MapPin, Trash2, Users, Wallet } from 'lucide-react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import './trips.css';

const demoTrip = { id: 'demo-1', destination: 'Manali, India', startDate: '2026-10-15', endDate: '2026-10-20', travellersNeeded: 4, budget: '₹5,000 – ₹10,000 / day', travelStyle: 'Adventure', interests: ['Nature', 'Photography'], activities: ['Trekking', 'Sightseeing'], accommodation: 'Hotels / Hostels', description: 'Mountain adventure with great views, local food and trekking.', status: 'upcoming' };
const formatDate = (value) => value ? new Date(`${value}T00:00:00`).toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' }) : 'Not set';
export default function TripDetails() {
  const { id } = useParams(); const navigate = useNavigate(); const [trip, setTrip] = useState(null);
  useEffect(() => { const saved = JSON.parse(localStorage.getItem('tripsync_trips') || '[]'); setTrip(saved.find((item) => item.id === id) || (id === 'demo-1' ? demoTrip : null)); }, [id]);
  const removeTrip = () => { if (!trip || !window.confirm('Delete this trip?')) return; const saved = JSON.parse(localStorage.getItem('tripsync_trips') || '[]').filter((item) => item.id !== trip.id); localStorage.setItem('tripsync_trips', JSON.stringify(saved)); navigate('/trips'); };
  if (!trip) return <div className="trip-card empty-trips"><h2>Trip not found</h2><p>This trip may have been removed.</p><Link to="/trips" className="primary-btn">Back to My Trips</Link></div>;
  return <div className="trip-page"><Link to="/trips" className="back-link"><ArrowLeft size={17}/> Back to My Trips</Link>
    <div className="details-hero"><div><span className="page-eyebrow">{trip.status === 'completed' ? 'COMPLETED TRIP' : 'UPCOMING TRIP'}</span><h1>{trip.destination}</h1><p>{trip.description || 'Your TripSync adventure.'}</p></div><div className="details-actions"><Link to="/discover" className="primary-btn">Find Matches</Link><button type="button" className="secondary-btn" onClick={removeTrip}><Trash2 size={16}/> Delete</button></div></div>
    <div className="details-grid"><main className="trip-main"><section className="trip-card"><h2>Trip overview</h2><div className="overview-grid"><div><CalendarDays size={18}/><span>Dates</span><strong>{formatDate(trip.startDate)} – {formatDate(trip.endDate)}</strong></div><div><Users size={18}/><span>Travellers</span><strong>{trip.travellersNeeded || 1} people needed</strong></div><div><Wallet size={18}/><span>Budget</span><strong>{trip.budget}</strong></div><div><MapPin size={18}/><span>Accommodation</span><strong>{trip.accommodation}</strong></div></div></section><section className="trip-card"><h2>Interests & activities</h2><div className="detail-section"><h3>Interests</h3><div className="mini-tags">{(trip.interests || []).map((item) => <span key={item}><Check size={12}/>{item}</span>)}</div></div><div className="detail-section"><h3>Activities</h3><div className="mini-tags">{(trip.activities || []).map((item) => <span key={item}><Check size={12}/>{item}</span>)}</div></div></section></main><aside className="trip-side"><section className="trip-card details-score"><span>Travel style</span><strong>{trip.travelStyle}</strong><p>This preference will be included when comparing your trip with other travellers.</p></section><section className="trip-card"><h3>Matching signals</h3><ul className="signal-list"><li><Check size={15}/> Destination</li><li><Check size={15}/> Date overlap</li><li><Check size={15}/> Budget</li><li><Check size={15}/> Interests</li><li><Check size={15}/> Activities</li></ul></section></aside></div>
  </div>;
}
